---
- hosts: all
  become: yes
  roles:
    - role: common_settings
- hosts: webapache
  become: yes
  roles:
    - role: web_httpd
    - role: web_wp
- hosts: webnginx
  become: yes
  roles:
    - role: web_nginx
- hosts: dbmysql
  roles: 
    - role: db_mysql