---
- hosts: all
  roles:
    - role: common_settings
- hosts: webapache
  roles:
    - role: web_httpd
    - role: web_wp
- hosts: webnginx
  roles:
    - role: web_nginx
- hosts: dbmysql
  roles: 
    - role: db_mysql
- hosts: hostmetrics
  roles:
    - role: prometheus_agent
    - role: filebeat_agent
- hosts: metricscollectors
  roles:
    - role: prometheus_server
- hosts: logservers
  roles:
    - role: elk_stack